# Exploring EBI gene2pheno data for parser

## Downloading data

Using the "all data" option/file. 

Latest data (created on-the-fly) can be downloaded from:
* API urls https://www.ebi.ac.uk/gene2phenotype/api/: `panel/{name}/download/` endpoint. Has "all data" option! Works programmatically and manually
* webpage https://www.ebi.ac.uk/gene2phenotype/download: currently manual clicks only. Has "all data" option. 

Static release files can be downloaded from the FTP site http://ftp.ebi.ac.uk/pub/databases/gene2phenotype/ (in the G2P_data_downloads subfolder). These releases included the "all data" file starting in Aug 2025. It updates on a monthly basis, according to the [README](http://ftp.ebi.ac.uk/pub/databases/gene2phenotype/README). However, I notice that the FTP site is sometimes slow on my computer (Firefox browser).

## Load data

In [1]:
## import packages for exploring here

## CX: allows multiple lines of code to print from one code block
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import pandas as pd

## for notebook viewing/debugging...
pd.options.display.max_columns = None

First try importing table as-is, to see what pandas sets column dtypes to be

In [2]:
## takes ~3s

df_url_all = pd.read_csv("https://www.ebi.ac.uk/gene2phenotype/api/panel/all/download/")

In [3]:
# df_url_all.columns = df_url_all.columns.str.replace(" ", "_")

df_url_all.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3826 entries, 0 to 3825
Data columns (total 24 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   g2p id                              3826 non-null   object
 1   gene symbol                         3826 non-null   object
 2   gene mim                            3823 non-null   float64
 3   hgnc id                             3826 non-null   int64
 4   previous gene symbols               3529 non-null   object
 5   disease name                        3826 non-null   object
 6   disease mim                         3031 non-null   float64
 7   disease MONDO                       3413 non-null   object
 8   allelic requirement                 3826 non-null   object
 9   cross cutting modifier              477 non-null    object
 10  confidence                          3826 non-null   object
 11  variant consequence                 3807 non-null   object
 12  variant types                       1139 non-null   object
 13  molecular mechanism                 3826 non-null   object
 14  molecular mechanism support         3826 non-null   object
 15  molecular mechanism categorisation  59 non-null     object
 16  molecular mechanism evidence        190 non-null    object
 17  phenotypes                          2502 non-null   object
 18  publications                        3727 non-null   object
 19  additional mined publications       2517 non-null   object
 20  panel                               3826 non-null   object
 21  comments                            241 non-null    object
 22  date of last review                 3826 non-null   object
 23  review                              0 non-null      float64
dtypes: float64(3), int64(1), object(20)
memory usage: 5.5 MB

In [4]:
df_url_all.head()

,g2p id,gene symbol,gene mim,hgnc id,previous gene symbols,disease name,disease mim,disease MONDO,allelic requirement,cross cutting modifier,confidence,variant consequence,variant types,molecular mechanism,molecular mechanism support,molecular mechanism categorisation,molecular mechanism evidence,phenotypes,publications,additional mined publications,panel,comments,date of last review,review
0,G2P00001,HMX1,142992.0,5017,H6; NKX5-3,HMX1-related oculoauricular syndrome,612109.0,MONDO:0012802,biallelic_autosomal,NaN,definitive,absent gene product,NaN,loss of function,inferred,NaN,NaN,HP:0000007; HP:0000356; HP:0000482; HP:0000505...,18423520; 25574057; 29140751,21417677; 31469246; 35946463,DD; Eye,NaN,2019-09-26 16:23:46+00:00,NaN
1,G2P00002,SLX4,613278.0,23845,BTBD12; FANCP; KIAA1784; KIAA1987,SLX4-related Fanconi anemia,613951.0,MONDO:0013499,biallelic_autosomal,NaN,definitive,absent gene product,NaN,loss of function,inferred,NaN,NaN,HP:0000007; HP:0000028; HP:0000085; HP:0000125...,21240275; 21240277,21476996; 23033263; 26841305; 30047418; 347541...,DD,NaN,2025-01-28 23:09:54+00:00,NaN
2,G2P00003,ARG1,608313.0,663,NaN,ARG1-related argininemia,207800.0,MONDO:0008814,biallelic_autosomal,NaN,definitive,absent gene product,NaN,loss of function,inferred,NaN,NaN,HP:0000007; HP:0000737; HP:0000752; HP:0001249...,10502833; 1463019; 1598908; 2365823; 7649538,15565656; 19052914; 19562505; 19936428; 213103...,DD,NaN,2015-07-22 16:14:07+00:00,NaN
3,G2P00004,ATR,601215.0,882,FRP1; MEC1; SCKL; SCKL1,ATR-related Seckel syndrome,210600.0,MONDO:0008869,biallelic_autosomal,NaN,strong,absent gene product,NaN,loss of function,inferred,NaN,NaN,HP:0000007; HP:0000028; HP:0000047; HP:0000175...,10889046; 12640452; 23111928; 30199583,10631133; 15279811; 21669506; 23144622; 272354...,DD; Skeletal,NaN,2025-01-27 14:24:27+00:00,NaN
4,G2P00005,FANCB,300515.0,3583,FAAP95; FAB; FLJ34064,FANCB-related Fanconi anemia,300514.0,MONDO:0010351,monoallelic_X_hemizygous,NaN,definitive,absent gene product,NaN,loss of function,inferred,NaN,NaN,HP:0000083; HP:0000100; HP:0000119; HP:0000707...,15502827; 16679491; 21910217; 22052692; 236135...,24416387; 31351673,DD; Skin,NaN,2024-08-20 14:13:58+00:00,NaN

The IDs are mutated/incorrect when they're imported as floats (add .0 to ends). 

I'd prefer if **the ID columns were imported as strings**. So reloading and setting column dtypes...

### Final loading

In [5]:
df_url_all = pd.read_csv("https://www.ebi.ac.uk/gene2phenotype/api/panel/all/download/",
                        dtype={
                            "gene mim": str,
                            "hgnc id": str,
                            "disease mim": str,
                        }
                        )

df_url_all.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3826 entries, 0 to 3825
Data columns (total 24 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   g2p id                              3826 non-null   object
 1   gene symbol                         3826 non-null   object
 2   gene mim                            3823 non-null   object
 3   hgnc id                             3826 non-null   object
 4   previous gene symbols               3529 non-null   object
 5   disease name                        3826 non-null   object
 6   disease mim                         3031 non-null   object
 7   disease MONDO                       3413 non-null   object
 8   allelic requirement                 3826 non-null   object
 9   cross cutting modifier              477 non-null    object
 10  confidence                          3826 non-null   object
 11  variant consequence                 3807 non-null   object
 12  variant types                       1139 non-null   object
 13  molecular mechanism                 3826 non-null   object
 14  molecular mechanism support         3826 non-null   object
 15  molecular mechanism categorisation  59 non-null     object
 16  molecular mechanism evidence        190 non-null    object
 17  phenotypes                          2502 non-null   object
 18  publications                        3727 non-null   object
 19  additional mined publications       2517 non-null   object
 20  panel                               3826 non-null   object
 21  comments                            241 non-null    object
 22  date of last review                 3826 non-null   object
 23  review                              0 non-null      float64
dtypes: float64(1), object(23)
memory usage: 6.0 MB

In [6]:
df_url_all.head()

,g2p id,gene symbol,gene mim,hgnc id,previous gene symbols,disease name,disease mim,disease MONDO,allelic requirement,cross cutting modifier,confidence,variant consequence,variant types,molecular mechanism,molecular mechanism support,molecular mechanism categorisation,molecular mechanism evidence,phenotypes,publications,additional mined publications,panel,comments,date of last review,review
0,G2P00001,HMX1,142992,5017,H6; NKX5-3,HMX1-related oculoauricular syndrome,612109,MONDO:0012802,biallelic_autosomal,NaN,definitive,absent gene product,NaN,loss of function,inferred,NaN,NaN,HP:0000007; HP:0000356; HP:0000482; HP:0000505...,18423520; 25574057; 29140751,21417677; 31469246; 35946463,DD; Eye,NaN,2019-09-26 16:23:46+00:00,NaN
1,G2P00002,SLX4,613278,23845,BTBD12; FANCP; KIAA1784; KIAA1987,SLX4-related Fanconi anemia,613951,MONDO:0013499,biallelic_autosomal,NaN,definitive,absent gene product,NaN,loss of function,inferred,NaN,NaN,HP:0000007; HP:0000028; HP:0000085; HP:0000125...,21240275; 21240277,21476996; 23033263; 26841305; 30047418; 347541...,DD,NaN,2025-01-28 23:09:54+00:00,NaN
2,G2P00003,ARG1,608313,663,NaN,ARG1-related argininemia,207800,MONDO:0008814,biallelic_autosomal,NaN,definitive,absent gene product,NaN,loss of function,inferred,NaN,NaN,HP:0000007; HP:0000737; HP:0000752; HP:0001249...,10502833; 1463019; 1598908; 2365823; 7649538,15565656; 19052914; 19562505; 19936428; 213103...,DD,NaN,2015-07-22 16:14:07+00:00,NaN
3,G2P00004,ATR,601215,882,FRP1; MEC1; SCKL; SCKL1,ATR-related Seckel syndrome,210600,MONDO:0008869,biallelic_autosomal,NaN,strong,absent gene product,NaN,loss of function,inferred,NaN,NaN,HP:0000007; HP:0000028; HP:0000047; HP:0000175...,10889046; 12640452; 23111928; 30199583,10631133; 15279811; 21669506; 23144622; 272354...,DD; Skeletal,NaN,2025-01-27 14:24:27+00:00,NaN
4,G2P00005,FANCB,300515,3583,FAAP95; FAB; FLJ34064,FANCB-related Fanconi anemia,300514,MONDO:0010351,monoallelic_X_hemizygous,NaN,definitive,absent gene product,NaN,loss of function,inferred,NaN,NaN,HP:0000083; HP:0000100; HP:0000119; HP:0000707...,15502827; 16679491; 21910217; 22052692; 236135...,24416387; 31351673,DD; Skin,NaN,2024-08-20 14:13:58+00:00,NaN

## Code chunks to explore column data

In [7]:
## just in case, check for duplicates

df_url_all[df_url_all.duplicated(keep=False)]

Empty DataFrame
Columns: [g2p id, gene symbol, gene mim, hgnc id, previous gene symbols, disease name, disease mim, disease MONDO, allelic requirement, cross cutting modifier, confidence, variant consequence, variant types, molecular mechanism, molecular mechanism support, molecular mechanism categorisation, molecular mechanism evidence, phenotypes, publications, additional mined publications, panel, comments, date of last review, review]
Index: []

In [8]:
## useful function
def check_if_contains(df, column_name, patterns):
    for i in patterns:
        temp = df[df[column_name].str.contains(pat=i, na=False)]
        if temp.size > 0:
            print(f'"{i}"')
            print(temp.shape)

In [9]:
df_url_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3826 entries, 0 to 3825
Data columns (total 24 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   g2p id                              3826 non-null   object
 1   gene symbol                         3826 non-null   object
 2   gene mim                            3823 non-null   object
 3   hgnc id                             3826 non-null   object
 4   previous gene symbols               3529 non-null   object
 5   disease name                        3826 non-null   object
 6   disease mim                         3031 non-null   object
 7   disease MONDO                       3413 non-null   object
 8   allelic requirement                 3826 non-null   object
 9   cross cutting modifier              477 non-null    object
 10  confidence                          3826 non-null   object
 11  variant consequence                 3807 non-null   object
 12  variant types                       1139 non-null   object
 13  molecular mechanism                 3826 non-null   object
 14  molecular mechanism support         3826 non-null   object
 15  molecular mechanism categorisation  59 non-null     object
 16  molecular mechanism evidence        190 non-null    object
 17  phenotypes                          2502 non-null   object
 18  publications                        3727 non-null   object
 19  additional mined publications       2517 non-null   object
 20  panel                               3826 non-null   object
 21  comments                            241 non-null    object
 22  date of last review                 3826 non-null   object
 23  review                              0 non-null      float64
dtypes: float64(1), object(23)
memory usage: 717.5+ KB

In [10]:
## record/association ID

df_url_all["g2p id"].nunique()

3826

In [11]:
## gene ID/name fields
df_url_all[df_url_all["gene mim"].isna()]

,g2p id,gene symbol,gene mim,hgnc id,previous gene symbols,disease name,disease mim,disease MONDO,allelic requirement,cross cutting modifier,confidence,variant consequence,variant types,molecular mechanism,molecular mechanism support,molecular mechanism categorisation,molecular mechanism evidence,phenotypes,publications,additional mined publications,panel,comments,date of last review,review
2816,G2P03790,TEDC1,NaN,20127,C14ORF80,TEDC1-related neurodevelopmental disorder with...,NaN,NaN,biallelic_autosomal,NaN,moderate,absent gene product; decreased gene product level,frameshift_variant_NMD_escaping; splice_region...,loss of function,inferred,NaN,39979680 -> functional_alteration: patient cel...,NaN,30842647; 39979680,NaN,DD,NaN,2025-11-05 10:36:49+00:00,NaN
2830,G2P03910,TMEM184B,NaN,1310,C22ORF5; DKFZP586A1024; FM08; HS5O6A; SLC51C2,TMEM184B-related neurodevelopmental disorder,NaN,NaN,monoallelic_autosomal,typically de novo,limited,altered gene product structure,missense_variant; splice_donor_variant_NMD_esc...,loss of function,evidence,NaN,40885185 -> function: biochemical,NaN,40885185,NaN,DD,NaN,2025-12-04 09:57:32+00:00,NaN
3059,G2P02168,MFSD6L,NaN,26656,FLJ35773,MFSD6L-related congenital cataract,NaN,MONDO:0005129,biallelic_autosomal,NaN,limited,altered gene product structure,inframe_deletion; inframe_insertion; missense_...,undetermined,inferred,NaN,NaN,HP:0000007; HP:0010864,22935719,NaN,Eye,NaN,2017-08-29 09:35:13+00:00,NaN

In [12]:
## disease ID/name fields

## all values in MONDO column have desired prefix
df_url_all[~ df_url_all["disease MONDO"].str.startswith("MONDO:", na=True)]

# rows with no disease ID
df_url_all[df_url_all["disease mim"].isna() & 
           df_url_all["disease MONDO"].isna()].shape[0]

check_if_contains(df_url_all, "disease name", [":", ";"])
# df_url_all[df_url_all["disease name"].str.contains(";", na=False)]

Empty DataFrame
Columns: [g2p id, gene symbol, gene mim, hgnc id, previous gene symbols, disease name, disease mim, disease MONDO, allelic requirement, cross cutting modifier, confidence, variant consequence, variant types, molecular mechanism, molecular mechanism support, molecular mechanism categorisation, molecular mechanism evidence, phenotypes, publications, additional mined publications, panel, comments, date of last review, review]
Index: []

223

":"
(4, 24)
";"
(1, 24)

In [13]:
df_url_all["allelic requirement"].value_counts()

allelic requirement
biallelic_autosomal           2002
monoallelic_autosomal         1582
monoallelic_X_hemizygous       174
monoallelic_X_heterozygous      58
mitochondrial                    7
monoallelic_X                    2
monoallelic_Y_hemizygous         1
Name: count, dtype: int64

In [14]:
df_url_all["cross cutting modifier"].value_counts()

df_url_all[df_url_all["cross cutting modifier"].notna()].head()

cross cutting modifier
restricted mutation set                                 288
potential secondary finding                              70
typically de novo                                        67
typically de novo; restricted mutation set               14
potential secondary finding; restricted mutation set     12
typically mosaic; restricted mutation set                 9
imprinted region                                          8
typically mosaic                                          3
imprinted region; restricted mutation set                 3
typified by incomplete penetrance                         2
typically de novo; typified by incomplete penetrance      1
Name: count, dtype: int64

,g2p id,gene symbol,gene mim,hgnc id,previous gene symbols,disease name,disease mim,disease MONDO,allelic requirement,cross cutting modifier,confidence,variant consequence,variant types,molecular mechanism,molecular mechanism support,molecular mechanism categorisation,molecular mechanism evidence,phenotypes,publications,additional mined publications,panel,comments,date of last review,review
19,G2P00021,COL1A1,120150,2197,OI4,COL1A1-related osteogenesis imperfecta spectrum,166220,MONDO:0008148,monoallelic_autosomal,restricted mutation set,definitive,altered gene product structure,NaN,dominant negative,inferred,NaN,NaN,HP:0000006; HP:0000007; HP:0000239; HP:0000260...,11286507; 12538651; 15024692; 15728585; 161376...,25633413; 30408804; 30614853; 30720562; 308380...,DD; Skin; Skeletal,NaN,2025-01-15 11:51:09+00:00,NaN
22,G2P00024,HRAS,190020,5173,HRAS1,HRAS-related Costello syndrome,218040,MONDO:0009026,monoallelic_autosomal,restricted mutation set,definitive,altered gene product structure,NaN,gain of function,inferred,NaN,NaN,HP:0000006; HP:0000083; HP:0000158; HP:0000179...,16170316; 16443854; 16835863; 17054105; 170566...,22098123; 22113246; 22495831; 22495892; 225102...,DD; Skin,NaN,2017-09-01 16:19:15+00:00,NaN
34,G2P00036,CBL,165360,1541,C-CBL; CBL2; RNF55,CBL-related Noonan syndrome-like disorder with...,613563,MONDO:0013308,monoallelic_autosomal,restricted mutation set,definitive,altered gene product structure,NaN,gain of function,inferred,NaN,NaN,HP:0000271; HP:0000369; HP:0000492; HP:0000494...,20543203; 20619386; 20694012,21750428; 24458550; 25283271; 25952305; 283431...,DD,NaN,2025-01-27 09:29:25+00:00,NaN
35,G2P00037,COL2A1,120140,2200,AOM; SEDC; STL1,COL2A1-related Kniest dysplasia,156550,MONDO:0007987,monoallelic_autosomal,restricted mutation set,definitive,altered gene product structure,NaN,dominant negative,inferred,NaN,NaN,HP:0000006; HP:0000023; HP:0000175; HP:0000272...,26443184; 26626311; 7849719; 7874117; 7981752;...,10406661; 11297324; 12205109; 14644246; 150765...,DD; Eye; Skeletal,NaN,2023-05-24 09:07:26+00:00,NaN
41,G2P00044,LRP5,603506,6697,BMND1; EVR1; EVR4; HBM; LR3; LRP7; OPPG; OPS; ...,LRP5-related osteopetrosis,601884,NaN,monoallelic_autosomal,restricted mutation set,definitive,altered gene product structure,inframe_deletion; inframe_insertion; missense_...,gain of function,inferred,NaN,NaN,HP:0000006; HP:0000405; HP:0000407; HP:0000689...,11741193; 12579474; 14727154,15141052; 15615112; 15824861; 15940380; 208552...,DD; Skeletal,NaN,2024-09-11 14:04:28+00:00,NaN

In [15]:
df_url_all["confidence"].value_counts()

confidence
definitive    2038
strong         858
limited        582
moderate       295
disputed        50
refuted          3
Name: count, dtype: int64

In [16]:
df_url_all["molecular mechanism"].value_counts()

molecular mechanism
loss of function                     2274
undetermined                         1220
gain of function                      194
dominant negative                     130
undetermined non-loss-of-function       8
Name: count, dtype: int64

In [17]:
## digging into new column molecular mechanism support
df_url_all["molecular mechanism support"].value_counts()

df_url_all[df_url_all["molecular mechanism support"] == "evidence"][0:5]

molecular mechanism support
inferred    3662
evidence     164
Name: count, dtype: int64

,g2p id,gene symbol,gene mim,hgnc id,previous gene symbols,disease name,disease mim,disease MONDO,allelic requirement,cross cutting modifier,confidence,variant consequence,variant types,molecular mechanism,molecular mechanism support,molecular mechanism categorisation,molecular mechanism evidence,phenotypes,publications,additional mined publications,panel,comments,date of last review,review
16,G2P00018,AGPS,603051,327,ADAP-S; ADAS; ADHAPS; ADPS; ALDHPSY,AGPS-related rhizomelic chondrodysplasia punctata,600121,MONDO:0010823,biallelic_autosomal,NaN,definitive,absent gene product; altered gene product stru...,frameshift_variant; missense_variant; splice_d...,loss of function,evidence,NaN,21990100 -> function: protein expression & 248...,HP:0000007; HP:0000260; HP:0000343; HP:0000463...,11152660; 21990100; 24849933; 35986576; 7807941,27616591; 33337545; 34229749; 35070570,DD; Eye; Skeletal,NaN,2026-01-27 12:40:55+00:00,NaN
61,G2P00064,VSX2,142993,1975,CHX10; HOX10; RET1,VSX2-related microphthalmia with cataracts and...,610092,MONDO:0012408,biallelic_autosomal,NaN,definitive,absent gene product; altered gene product stru...,frameshift_variant; missense_variant; splice_r...,loss of function,evidence,interaction-disrupting LOF:evidence,"10932181 -> function: biochemical, protein int...",HP:0000007; HP:0000518; HP:0000568; HP:0000589,10932181; 15257456; 24532057; 39610658; 8630490,20057906; 20215382; 24001013; 24033328; 248596...,DD; Eye,NaN,2026-01-27 12:40:31+00:00,NaN
73,G2P00078,PIGV,610274,26031,FLJ20477; GPI-MT-II; PIG-V,PIGV-related hyperphosphatasia with intellectu...,239300,MONDO:0009398,biallelic_autosomal,NaN,definitive,altered gene product structure,inframe_deletion; inframe_insertion; missense_...,loss of function,evidence,NaN,20802478 -> function: protein expression; func...,HP:0000007; HP:0000175; HP:0000204; HP:0000219...,17351347; 20802478; 22228761; 33402532; 40799153,21739589; 22315194; 24129430; 27177984; 288172...,DD; Skeletal,NaN,2026-01-27 12:41:33+00:00,NaN
82,G2P00087,GDF5,601146,4220,BMP14; CDMP1,"GDF5-related acromesomelic chondrodysplasia, G...",200700,MONDO:0008703,biallelic_autosomal,NaN,definitive,uncertain,NaN,loss of function,evidence,LOF due to protein mislocalisation:evidence,"9288098 -> function: biochemical, protein expr...",HP:0000007; HP:0000954; HP:0001156; HP:0001162...,12121354; 12124730; 12357473; 12900894; 162226...,12407712; 12687891; 18283415; 18979166; 258208...,DD; Skeletal,NaN,2026-01-27 12:56:33+00:00,NaN
102,G2P00108,INPP5E,613037,21474,CORS1; JBTS1; PHARBIN; PPI5PIV,INPP5E-related intellectual development disord...,610156,NaN,biallelic_autosomal,NaN,definitive,absent gene product; altered gene product stru...,frameshift_variant; stop_gained_NMD_escaping,loss of function,evidence,LOF due to protein mislocalisation:evidence,"19668215 -> function: protein expression, bioc...",HP:0000007; HP:0000054; HP:0000505; HP:0000518...,19668215; 31173343; 34211432,26748598; 29987673; 38806661,DD; Eye,NaN,2026-01-29 11:44:03+00:00,NaN

In [18]:
## digging into molecular mechanism evidence

## all "evidence" have evidence column too
df_url_all[(df_url_all["molecular mechanism support"] == "evidence") & 
           (df_url_all["molecular mechanism evidence"].isna())].shape[0]

## some "inferred" have evidence column
df_url_all[(df_url_all["molecular mechanism support"] == "inferred") & 
           (df_url_all["molecular mechanism evidence"].notna())].shape[0]

df_url_all["molecular mechanism evidence"].nunique()
df_url_all[df_url_all["molecular mechanism evidence"].notna()]["molecular mechanism evidence"].unique()[0:5]
# df_url_all[df_url_all["molecular mechanism evidence"].str.contains("39315527", na=False)]

0

26

186

array(['21990100 -> function: protein expression & 24849933 -> function: protein expression, biochemical; functional_alteration: patient cells & 35986576 -> function: biochemical',
       '10932181 -> function: biochemical, protein interaction & 24532057 -> functional_alteration: patient cells; rescue: cell culture model & 8630490 -> models: non-human model organism & 39610658 -> models: non-human model organism',
       '20802478 -> function: protein expression; functional_alteration: non patient cells, patient cells & 22228761 -> function: protein expression; functional_alteration: non patient cells; rescue: cell culture model & 33402532 -> function: protein interaction; models: non-human model organism & 40799153 -> function: protein expression, biochemical; functional_alteration: patient cells; rescue: cell culture model',
       '9288098 -> function: biochemical, protein expression, protein interaction; functional_alteration: non patient cells & 12357473 -> function: protein expression & 23812741 -> function: protein expression; functional_alteration: non patient cells',
       '19668215 -> function: protein expression, biochemical; functional_alteration: non patient cells; rescue: cell culture model'],
      dtype=object)

In [28]:
## digging into changed column molecular mechanism categorisation

## mostly when support=="evidence"
df_url_all[(df_url_all["molecular mechanism support"] == "evidence") & 
           (df_url_all["molecular mechanism categorisation"].notna())].shape[0]
## "inferred"
df_url_all[(df_url_all["molecular mechanism support"] == "inferred") & 
           (df_url_all["molecular mechanism categorisation"].notna())].shape[0]

df_url_all["molecular mechanism categorisation"].unique().tolist()

df_url_all[df_url_all["molecular mechanism categorisation"].notna()][0:5]

55

4

[nan,
 'interaction-disrupting LOF:evidence',
 'LOF due to protein mislocalisation:evidence',
 'loss of activity LOF:evidence',
 'destabilising LOF:evidence',
 'loss of activity LOF:evidence; interaction-disrupting LOF:evidence',
 'destabilising LOF:evidence; interaction-disrupting LOF:evidence',
 'assembly-mediated dominant negative:evidence',
 'interaction-disrupting LOF:inferred',
 'loss of activity LOF:inferred',
 'destabilising LOF:evidence; LOF due to protein mislocalisation:evidence',
 'destabilising LOF:inferred',
 'other GOF:evidence',
 'assembly-mediated GOF:evidence',
 'competitive dominant-negative:evidence',
 'LOF due to protein mislocalisation:inferred',
 'interaction-disrupting LOF:evidence; LOF due to protein mislocalisation:evidence',
 'loss of activity LOF:evidence; LOF due to protein mislocalisation:evidence',
 'local LOF leading to overall GOF:evidence',
 'interaction-disrupting LOF:evidence; LOF due to protein mislocalisation:evidence; loss of activity LOF:evidence',
 'loss of activity LOF:evidence; LOF due to protein mislocalisation:evidence; destabilising LOF:evidence',
 'loss of activity LOF:evidence; destabilising LOF:evidence']

,g2p id,gene symbol,gene mim,hgnc id,previous gene symbols,disease name,disease mim,disease MONDO,allelic requirement,cross cutting modifier,confidence,variant consequence,variant types,molecular mechanism,molecular mechanism support,molecular mechanism categorisation,molecular mechanism evidence,phenotypes,publications,additional mined publications,panel,comments,date of last review,review
61,G2P00064,VSX2,142993,1975,CHX10; HOX10; RET1,VSX2-related microphthalmia with cataracts and...,610092,MONDO:0012408,biallelic_autosomal,NaN,definitive,absent gene product; altered gene product stru...,frameshift_variant; missense_variant; splice_r...,loss of function,evidence,interaction-disrupting LOF:evidence,"10932181 -> function: biochemical, protein int...",HP:0000007; HP:0000518; HP:0000568; HP:0000589,10932181; 15257456; 24532057; 39610658; 8630490,20057906; 20215382; 24001013; 24033328; 248596...,DD; Eye,NaN,2026-01-27 12:40:31+00:00,NaN
82,G2P00087,GDF5,601146,4220,BMP14; CDMP1,"GDF5-related acromesomelic chondrodysplasia, G...",200700,MONDO:0008703,biallelic_autosomal,NaN,definitive,uncertain,NaN,loss of function,evidence,LOF due to protein mislocalisation:evidence,"9288098 -> function: biochemical, protein expr...",HP:0000007; HP:0000954; HP:0001156; HP:0001162...,12121354; 12124730; 12357473; 12900894; 162226...,12407712; 12687891; 18283415; 18979166; 258208...,DD; Skeletal,NaN,2026-01-27 12:56:33+00:00,NaN
102,G2P00108,INPP5E,613037,21474,CORS1; JBTS1; PHARBIN; PPI5PIV,INPP5E-related intellectual development disord...,610156,NaN,biallelic_autosomal,NaN,definitive,absent gene product; altered gene product stru...,frameshift_variant; stop_gained_NMD_escaping,loss of function,evidence,LOF due to protein mislocalisation:evidence,"19668215 -> function: protein expression, bioc...",HP:0000007; HP:0000054; HP:0000505; HP:0000518...,19668215; 31173343; 34211432,26748598; 29987673; 38806661,DD; Eye,NaN,2026-01-29 11:44:03+00:00,NaN
273,G2P00284,ALPL,171760,438,HOPS; TNALP; TNAP; TNSALP,ALPL-related hypophosphatasia,NaN,MONDO:0018570,biallelic_autosomal,NaN,definitive,absent gene product; altered gene product stru...,inframe_deletion; inframe_insertion; missense_...,loss of function,evidence,loss of activity LOF:evidence,"33093890 -> function: biochemical, protein exp...",HP:0000007; HP:0000121; HP:0000164; HP:0000592...,14982838; 3174660; 33093890; 33101980; 33160095,30929401; 31707452; 32025537; 32088736; 326948...,DD; Skeletal,NaN,2026-01-27 14:21:30+00:00,NaN
294,G2P00306,INPP5E,613037,21474,CORS1; JBTS1; PHARBIN; PPI5PIV,INPP5E-related Joubert syndrome,213300,MONDO:0008944,biallelic_autosomal,NaN,definitive,altered gene product structure; uncertain,missense_variant,loss of function,evidence,loss of activity LOF:evidence,19668216 -> function: biochemical; functional_...,HP:0000007; HP:0000107; HP:0000158; HP:0000256...,19668215; 19668216; 23022135; 27401686; 29052317,20446224; 23034536; 23386033; 25818971; 264901...,DD; Eye,NaN,2026-01-29 11:07:29+00:00,NaN

In [31]:
## publications column doesn't have prefixes
check_if_contains(df_url_all, "publications", ["PMID", ":", "_"])

Empty DataFrame
Columns: [g2p id, gene symbol, gene mim, hgnc id, previous gene symbols, disease name, disease mim, disease MONDO, allelic requirement, cross cutting modifier, confidence, variant consequence, variant types, molecular mechanism, molecular mechanism support, molecular mechanism categorisation, molecular mechanism evidence, phenotypes, publications, additional mined publications, panel, comments, date of last review, review]
Index: []

In [35]:
df_url_all[df_url_all["comments"].notna()].head()
df_url_all[df_url_all["comments"].notna()]["comments"].unique()[0:5]

,g2p id,gene symbol,gene mim,hgnc id,previous gene symbols,disease name,disease mim,disease MONDO,allelic requirement,cross cutting modifier,confidence,variant consequence,variant types,molecular mechanism,molecular mechanism support,molecular mechanism categorisation,molecular mechanism evidence,phenotypes,publications,additional mined publications,panel,comments,date of last review,review
118,G2P00124,KCNE1,176261,6240,ISK; JLNS2; LQT5; MINK,KCNE1-related Jervell and Lange-Nielsen syndrome,612347,MONDO:0012871,biallelic_autosomal,potential secondary finding,strong,altered gene product structure,inframe_deletion; inframe_insertion; missense_...,undetermined,inferred,NaN,NaN,HP:0000007; HP:0000407; HP:0001279; HP:0001657,10973849; 16461811; 19716085; 30461122; 319413...,11802537; 12443809; 16414944; 16929947; 245738...,DD; Cardiac,KCNE1-related JLNS is due to altered gene prod...,2024-04-05 12:05:01+00:00,NaN
311,G2P00323,FLNA,300017,3754,ABP-280; FLN; FLN1; OPD1; OPD2,FLNA-related congenital idiopathic intestinal ...,300048,MONDO:0010232,monoallelic_X_hemizygous,NaN,definitive,increased gene product level,NaN,undetermined,inferred,NaN,NaN,HP:0000126; HP:0000316; HP:0000319; HP:0000369...,18854860; 23037936; 8644737,15194946; 16299064; 20730588; 21320118; 238736...,DD,Part of contiguous gene duplication,2015-07-22 16:14:27+00:00,NaN
388,G2P00400,FBXW4,608071,10847,DACTYLIN; FBW4; SHFM3,FBXW4-related split-hand and foot malformation,246560,MONDO:0009525,monoallelic_autosomal,NaN,limited,increased gene product level,NaN,undetermined,inferred,NaN,NaN,HP:0000006; HP:0000007; HP:0000089; HP:0000160...,12913067; 12974740; 16691619; 16761290; 292630...,15232212; 16235095; 17120235; 19584065; 214850...,DD; Skeletal,Part of a contiguous gene duplication,2023-05-24 09:07:27+00:00,NaN
766,G2P00792,ZNF750,610226,25843,FLJ13841; ZFP750,ZNF750-related seborrhea-like dermatitis with ...,610227,MONDO:0012446,monoallelic_autosomal,NaN,moderate,absent gene product,NaN,loss of function,inferred,NaN,NaN,HP:0000006; HP:0000962; HP:0001051,16751772,NaN,DD; Skin,Large number of affected individuals and famil...,2025-09-26 12:00:50+00:00,NaN
813,G2P00841,PTPN11,176876,9644,BPTP3; NS1; PTP2C; SH-PTP2; SHP-2; SHP2,PTPN11-related Noonan syndrome with multiple l...,151100,MONDO:0100082,monoallelic_autosomal,NaN,definitive,altered gene product structure,inframe_deletion; inframe_insertion; missense_...,undetermined,inferred,NaN,NaN,HP:0000006; HP:0000028; HP:0000047; HP:0000054...,11992261; 12058348; 12161596; 14634749; 149615...,25156961; 25425531; 25585602; 25595571; 257082...,DD; Skin; Cardiac,Expert review done on 12/01/2022; Noonan syndr...,2025-09-09 09:58:55+00:00,NaN

array(['KCNE1-related JLNS is due to altered gene product sequence. Inheritance is autosomal recessive. Homozygous or compound heterozygous KCNE1 variants cause JLNS through loss of function (PMID: 9354783). The majority of JLNS patients have biallelic KCNQ1 variants (JLNS1), only a minority have JLNS2 caused by biallelic KCNE1 variants (PMID: 16461811). The KCNE1 protein (previous names LQT5, mink, IsK) functions as a regulatory subunit of KCNQ1. It has 7 annotated exons but only one is protein coding (PMID: 30461122). A small number of variants have been reported, mainly missense and inframe indels. In more recent studies, 4 nonsense variants have also been reported (PMID: 30461122; 31941373). However, in one of these studies (PMID: 30461122), patients were ascertained for deafness and QT prolongation is either variable or not reported in some family members. The authors did not carry out functional studies to determine the effect of these variants on mRNA but suggest that given there is only one coding exon, these nonsense variants would be unlikely to result in nonsense mediated decay. The phenotype of KCNE1-related JLNS2 appears to be milder than JLNS1 (caused by biallelic KCNQ1 variants) (PMID: 16461811; 31941373) Heterozygous variants in KCNE1 have been associated with LQT syndrome without deafness. However, Roberts et al observed a low ECG penetrance in these individuals with the majority not manifesting clinically (PMID: 31941373). ClinGen classified the gene disease association, KCNE1 and JLNS2, as Moderate stating that although there was a large amount of experimental evidence and no contradictory evidence, more case level evidence was required to reach a Definitive classification.; KCNE1-related JLNS is due to altered gene product sequence. Inheritance is autosomal recessive. Homozygous or compound heterozygous KCNE1 variants cause JLNS through loss of function (PMID: 9354783). The majority of JLNS patients have biallelic KCNQ1 variants (JLNS1), only a minority have JLNS2 caused by biallelic KCNE1 variants (PMID: 16461811). The KCNE1 protein (previous names LQT5, mink, IsK) functions as a regulatory subunit of KCNQ1. It has 7 annotated exons but only one is protein coding (PMID: 30461122). A small number of variants have been reported, mainly missense and inframe indels. In more recent studies, 4 nonsense variants have also been reported (PMID: 30461122; 31941373). However, in one of these studies (PMID: 30461122), patients were ascertained for deafness and QT prolongation is either variable or not reported in some family members. The authors did not carry out functional studies to determine the effect of these variants on mRNA but suggest that given there is only one coding exon, these nonsense variants would be unlikely to result in nonsense mediated decay. The phenotype of KCNE1-related JLNS2 appears to be milder than JLNS1 (caused by biallelic KCNQ1 variants) (PMID: 16461811; 31941373) Heterozygous variants in KCNE1 have been associated with LQT syndrome without deafness. However, Roberts et al observed a low ECG penetrance in these individuals with the majority not manifesting clinically (PMID: 31941373). ClinGen classified the gene disease association, KCNE1 and JLNS2, as Moderate stating that although there was a large amount of experimental evidence and no contradictory evidence, more case level evidence was required to reach a Definitive classification.',
       'Part of contiguous gene duplication',
       'Part of a contiguous gene duplication',
       'Large number of affected individuals and family segregation data.',
       'Expert review done on 12/01/2022; Noonan syndrome with multiple lentigines (NSML, previously known as LEOPARD syndrome) is inherited as an autosomal dominant condition. Missense variants in PTPN11 are responsible for the majority of cases. Rare cases have been attributed to variants in RAF1, BRAF, and MAP2K1. There is no definite evidence of PTPN11 variants causing isolated cardiac disease without other features of NSML, but the syndromic phenotype can be subtle and may be underdiagnosed. This suggests that cardiac involvement can be the initial presentation in some cases, and PTPN11 should be considered in the differential diagnosis of HCM. PTPN11 variants associated with NSML are clustered in the phosphotyrosine phosphatase (PTP) domain and have been shown to inhibit phosphatase activity. Since null variants have not been associated with the NSML phenotype, it has been suggested that NSML is caused by a dominant-negative effect rather than simple loss of function, possibly due to altered interaction between PTPN11 and binding partners. Allelic disorders include Noonan syndrome, caused by gain-of-function variants in PTPN11, and metachondromatosis, caused by loss-of-function PTPN11 variants.'],
      dtype=object)

In [36]:
## no rows with non-NA review to look at possible values
df_url_all[df_url_all["review"].notna()]

Empty DataFrame
Columns: [g2p id, gene symbol, gene mim, hgnc id, previous gene symbols, disease name, disease mim, disease MONDO, allelic requirement, cross cutting modifier, confidence, variant consequence, variant types, molecular mechanism, molecular mechanism support, molecular mechanism categorisation, molecular mechanism evidence, phenotypes, publications, additional mined publications, panel, comments, date of last review, review]
Index: []

## Notes on parsing data to create documents

Reordered for what makes sense to put together. <mark>Highlight</mark> means this column is important for ingest

### Gene subject section

<mark>**hgnc id**</mark>: single ID, no prefix. No NA so easier to use (need to assign dtype to be string, otherwise may default load as int)

---

**gene mim** (a few NA): OMIM ID for gene (single ID), no prefix. NodeNorm does recognize these (need to assign dtype to be string, otherwise may default load as float)

**gene symbol**: str. "HGNC-assigned gene symbol" (according to Data_download_format txt file)

**previous gene symbols**: "; "-delimited.

### Disease object section

<mark>**disease mim**</mark> (some NA): OMIM ID for disease ("or highly similar" according to Data_download_format txt file). Single ID, no prefix. Used to find orphanet IDs mixed in (prefix `Orphanet:`) but haven't seen as of 2025-12. (need to assign dtype to be string, otherwise may default load as int)

<mark>**disease MONDO**</mark> (some NA): MONDO ID for disease ("or highly similar" according to Data_download_format txt file). Already Translator-formatted CURIE

**disease name**: Previously reviewed and didn't find any IDs, did find potential delimiters (`:`, `;`). Previously found surrounding whitespace to strip

### Association section

---

**Content**

<mark>**g2p id**</mark>: resource's unique stable ID for each record/row (according to Data_download_format txt file, G2P webpage for single record) => use to generate links to edge info. Current format: https://www.ebi.ac.uk/gene2phenotype/lgd/G2P03386


<mark>**allelic requirement**</mark>: required genotype (according to G2P webpage for single record). str (categorical). [G2P website](https://www.ebi.ac.uk/gene2phenotype/about/terminology) says these are synonyms of HPO "mode of inheritance terms", which seem to be from the [inheritance part of the ontology](https://hpo.jax.org/browse/term/HP:0000005). I've included a mapping table in reference section.

<mark>**confidence**</mark>: confidence that the association is real (according to G2P webpage for panel). [G2P website](https://www.ebi.ac.uk/gene2phenotype/about/terminology) has definitions of terms. str (categorical)
- OLD biolink note: there's an association-slot `has confidence level`. But there's also an entity `confidence level` that's supposed to have values from CIO. Are G2P's terms okay, or are they supposed to be mapped to ontology terms like CIO/SEPIO? (which...may be a loss of info compared to G2P's term definitions)

<mark>**molecular mechanism**</mark>: mechanism of how gene's variants causes disease (according to G2P webpage for single record). str (categorical). [G2P website](https://www.ebi.ac.uk/gene2phenotype/about/terminology) has definitions of terms

<mark>**publications**</mark> (some NA): reviewed to create this row/association (according to Data_download_format file). These are PMIDs with no prefix (based on G2P webpage for single record). Can be "; "-delimited

<mark>**date of last review**</mark>: date the record was modified or reviewed (according to Data_download_format txt file). In single-record webpage, this is called "Last Updated On".

---

**cross cutting modifier** (lots of NA!): additional info relevant to gene-disease inheritance (according to G2P webpage for single record). Can be "; "-delimited, otherwise would be categorical. [G2P website](https://www.ebi.ac.uk/gene2phenotype/about/terminology#cross-cutting-modifier-section) has definitions of terms and says these are HPO inheritance qualifier terms "when available" ([this part of ontology](https://hpo.jax.org/browse/term/HP:0034335)). But I previously found some terms are custom. I didn't try mapping these.

<br>

**variant consequence** (some NA): consequences of reported variants on product (protein or RNA) (according to G2P webpage for single record). Can be "; "-delimited, otherwise would be categorical. [G2P website](https://www.ebi.ac.uk/gene2phenotype/about/terminology) has definitions of terms and SO mappings. 

**variant types** (lots of NA!): associated with gene-disease pair (according to G2P webpage for single record). Can be "; "-delimited, otherwise would be categorical. [G2P website](https://www.ebi.ac.uk/gene2phenotype/about/terminology) has definitions of terms and SO mappings (large table!). **>100 UNIQUE VALUES (SINGLE, MIX OF TERMS). I don't think using this as a qualifier is a good idea - it's confusing**
* OLD biolink note: this info kinda exists in biolink as predicates for variant-gene relationships.

<br>

**molecular mechanism support** (new Aug 2025): seems to say how molecular mechanism was decided. But not sure exactly what this means/what methods - maybe in paper? str (categorical): "inferred" or "evidence".
"inferred" does show up on record webpage. Ex: "Molecular mechanism" > "Mechanism" will say "loss of function (inferred)".
Unclear how "evidence" alone would show up on webpage - rows always have "molecular mechanism evidence" value that shows up as "Molecular mechanism" > "Evidence" (current ex:  https://www.ebi.ac.uk/gene2phenotype/lgd/G2P00018)

**molecular mechanism categorisation** (new Aug 2025; **VERY SPARSE**): more detailed mechanism info, structured (displayed in single-record webpage as a table). 
- key: term from the ["molecular mechanism synopsis" section of terminology page](https://www.ebi.ac.uk/gene2phenotype/about/terminology#mechanism-synopsis-section). Separator between key and value is ":" 
- value: either 'evidence' or 'inferred' (no missing values, usually "evidence"). 
- Can have multiple key-value pairs ("; "-delimited). Each key-value pair becomes one row in molecular mechanism -> categorisation section of single-record webpage. 

**molecular mechanism evidence** (**VERY SPARSE**): "types of evidence available to support reported mechanism", according to Data download format txt. 
Has value in all rows where "molecular mechanism support" == "evidence" and a few rows where == "inferred".
complicated structure, is displayed in single-record webpages as a table under "Molecular mechanism" > "Evidence" (current ex: https://www.ebi.ac.uk/gene2phenotype/lgd/G2P00064)
- `publication_ID -> functional studies` (delimiter is " -> "). Functional studies key:value pairs are described in ["molecular mechanism evidence types" section of terminology page](https://www.ebi.ac.uk/gene2phenotype/about/terminology#mechanism-evidence-section).
  - key: class (enum). Separator between key and value is ":".
  - value: "evidence type". Possible value depends on key.
  - can have multiple key-value pairs ("; "-delimited) for 1 publication ID. Becomes different bullet points in row 
- can have info from multiple publications (" & "-delimited). Become different rows

<br>

**additional mined publications** (some NA): mined from PubMed but not reviewed yet (according to Data_download_format file). These are PMIDs with no prefix (based on G2P webpage for single record). Can be "; "-delimited

<br>

**phenotypes** (some NA): HPO IDs (already Translator-formatted CURIE) for phenotypes reported by the publications (according to G2P webpage for single record). Can be "; "-delimited
- based on G2P website, these are organized/assigned to specific gene-disease records...so I'm keeping as a part of the gene-disease association, rather than creating diff objects for gene-phenotype (if I did this, it would be a separate function)

<br>

**panel**: the G2P panels this record is assigned to (according to Data_download_format txt file). Can be "; "-delimited, otherwise would be categorical.
- map (str.replace) values to match G2P webpage for single record
  - "DD" = "Developmental disorders"
  - add " disorders" to end: "Cancer", "Cardiac", "Eye", "Skeletal", "Skin"
  - keep as-is: "Hearing loss"
    
    
**comments** (**VERY SPARSE**): additional comments from curation team (according to Data_download_format txt file). Appears to be free-text (sometimes short, sometimes very long). Sometimes has surrounding whitespace to strip 

**review** (new Aug 2025): indicates when record is under review (according to Data_download_format txt file). Don't know what the possible values are (boolean?) because I've only seen the column be all NA so far.

**Format updates since notebook originally written:**

**Nov 2025**

Added new column `additional mined publications`

**Aug 2025**

added/augmented notes for `variant types`, `molecular mechanism evidence`, `date of last review`

analyzed format changes, took notes on:
- old `molecular mechanism categorisation` column -> now `molecular mechanism support`
- new `molecular mechanism categorisation` content
- new `review` column

Filename change: DataDownloadFormat => Data_download_format

---

__Allelic requirement terms__

Mapping issues in HP (**bolded**) fixed: https://github.com/obophenotype/human-phenotype-ontology/issues/11243. Should match [2024 GenCC paper](https://www.gimjournal.org/article/S1098-3600(23)01045-6/fulltext) on harmonizing terminology


| G2P | HPO name | HPO ID | Exact synonym? | 
| :- | :- | :- | :- |
| biallelic_autosomal | Autosomal recessive inheritance | HP:0000007 | Yes |
| monoallelic_autosomal | Autosomal dominant inheritance | HP:0000006 | Yes |
| biallelic_PAR | Pseudoautosomal recessive inheritance | HP:0034341 | Yes |
| monoallelic_PAR | Pseudoautosomal dominant inheritance | HP:0034340 | Yes |
| mitochondrial | Mitochondrial inheritance | HP:0001427 | Yes |
| monoallelic_Y_hemizygous | Y-linked inheritance | HP:0001450 | Yes |
| **monoallelic_X** | X-linked inheritance | HP:0001417 | Yes |
| **monoallelic_X_hemizygous** | X-linked recessive inheritance | HP:0001419 | Yes |
| **monoallelic_X_heterozygous** | X-linked dominant inheritance | HP:0001423 | Yes |

## Other ideas/notes

Would do value-mapping using static dicts? Which would be brittle/work to maintain

* "variant consequence": create new column(s) for SO mapping (value is ID or labels, or a list of dict for ID/label pairs)
* "variant types": create new column(s) for SO mapping


"G2P records are Locus-Genotype-Mechanism-Disease-Evidence (LGMDE) threads describing gene-disease associations" -> this is what a unique row is from resource POV (ref: homepage table "Total LGMDE Records" info (i) button)


str split method will create single-element arrays if no delimiter found